sudo: required
language: go
go:
- master
services:
- docker
before_install:
- docker-compose pull
script:
- docker-compose up
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: bin/sha1dir.linux
  on:
    repo: ujenmr/sha1dir
