sudo: required
language: go
dist: trusty

go:
  - master

script:
  - go test ./... 
  - go build -o bin/sha1dir.linux main.go

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: bin/sha1dir.linux
  skip_cleanup: true
  on:
    tags: true
